# Generated by Django 5.2.8 on 2026-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='gattaran', max_length=50)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255)),
                ('target_region', models.CharField(blank=True, db_index=True, max_length=255)),
                ('establishment_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('representative_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('contract_status', models.CharField(blank=True, db_index=True, max_length=100)),
                ('representative_phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('company_category', models.CharField(blank=True, db_index=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('unique_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
