# Generated by Django 5.2.8 on 2026-02-04 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolead',
            name='representative_phone_norm',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MacroRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('command', 'Comando'), ('api', 'API'), ('csv', 'CSV')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('running', 'Executando'), ('success', 'Sucesso'), ('error', 'Erro')], db_index=True, default='running', max_length=20)),
                ('source', models.CharField(default='gattaran', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_collected', models.PositiveIntegerField(default=0)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('ignored_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
