# Generated by Codex on 2026-02-04

import re

from django.db import migrations


def _normalize_phone(value: str) -> str:
    digits = re.sub(r"\D", "", value or "")
    if digits.startswith("55") and len(digits) > 11:
        return digits
    if len(digits) in (10, 11):
        return "55" + digits
    return digits


def forward_fill_phone_norm(apps, schema_editor):
    MacroLead = apps.get_model("macros", "MacroLead")
    for lead in MacroLead.objects.all().only("id", "representative_phone", "representative_phone_norm"):
        normalized = _normalize_phone(lead.representative_phone)
        if lead.representative_phone_norm != normalized:
            lead.representative_phone_norm = normalized
            lead.save(update_fields=["representative_phone_norm"])


def backward_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("macros", "0002_macrolead_representative_phone_norm_macrorun"),
    ]

    operations = [
        migrations.RunPython(forward_fill_phone_norm, backward_noop),
    ]
