# Generated by Django 5.2.8 on 2026-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0003_backfill_macrolead_phone_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolead',
            name='lead_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
