# Generated by Django 5.2.8 on 2026-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0004_macrolead_lead_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolead',
            name='is_blocked_number',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
