# Generated by Django 5.2.8 on 2026-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0005_macrolead_is_blocked_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolead',
            name='business_99_status',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
