# Generated by Django 5.2.8 on 2026-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0008_macrorun_execution_id_and_dedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolead',
            name='signatory_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='macrolead',
            name='store_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
