# Generated by Django 5.2.8 on 2026-09-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0012_blockedcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolead',
            name='export_channel',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
