# Generated by Django 5.2.8 on 2026-09-19 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0013_macrolead_export_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersGrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(db_index=True, max_length=40)),
                ('brand_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('shop_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('grupo_offline', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('bdm_online', models.CharField(blank=True, max_length=120)),
                ('bd_username_offline', models.CharField(blank=True, max_length=120)),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='periodo (AAAA-MM)')),
                ('complete_orders', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gmv', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('shop_id', 'period'), name='unique_shop_period_orders_growth')],
            },
        ),
        migrations.CreateModel(
            name='OrdersGrowthRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Executando'), ('success', 'Sucesso'), ('error', 'Erro')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('execution_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('period', models.CharField(blank=True, max_length=7)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_growth_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
