# Generated by Django 5.2.8 on 2026-09-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0014_ordersgrowthrecord_ordersgrowthrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersgrowthrecord',
            name='period',
            field=models.CharField(db_index=True, max_length=10, verbose_name='periodo (AAAA-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='ordersgrowthrun',
            name='period',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
