# Generated by Django 5.2.8 on 2026-09-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0015_alter_ordersgrowthrecord_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolead',
            name='import_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='macros.macrorun'),
        ),
    ]
