# Generated by Django 5.2.8 on 2026-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0017_macroexportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroexportlog',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
