# Generated by Django 5.2.8 on 2026-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text='Use placeholders como {nome}, {valor}, {vencimento}, {meses}, {link}'),
        ),
    ]
