# Generated by Django 5.2.8 on 2025-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da mensalidade'),
        ),
    ]
