# Generated by Django 5.2.8 on 2026-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_default_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='recurring_months',
            field=models.PositiveIntegerField(default=1, verbose_name='Meses de recorrencia'),
        ),
    ]
