# Generated by Django 5.2.8 on 2026-04-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_recurring_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereco'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='client',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
    ]
