# Generated by Django 5.2.8 on 2026-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='asaas_checkout_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billing',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billing',
            name='billing_type',
            field=models.CharField(choices=[('CREDIT_CARD', 'Cartao de credito'), ('PIX', 'Pix'), ('BOLETO', 'Boleto')], default='CREDIT_CARD', max_length=30),
        ),
        migrations.AddField(
            model_name='billing',
            name='charge_type',
            field=models.CharField(choices=[('DETACHED', 'Avulsa'), ('INSTALLMENT', 'Parcelada'), ('RECURRENT', 'Recorrente')], default='RECURRENT', max_length=30),
        ),
        migrations.AddField(
            model_name='billing',
            name='recurring_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='billing',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
