from django.urls import path

from .views import (
    macro_api_import,
    macro_collect,
    macro_delete_all,
    macro_delete_blocked,
    macro_delete_filtered,
    macro_delete_run_item,
    macro_delete_runs,
    macro_delete_source,
    macro_toggle_phone_block,
    macro_download_local_agent_bat,
    macro_download_local_agent_exe,
    macro_download_local_agent_mac,
    macro_download_local_agent_py,
    macro_export_csv,
    macro_export_xlsx,
    macro_import_csv,
    macro_list,
)

urlpatterns = [
    path("", macro_list, name="macro_list"),
    path("coleta/", macro_collect, name="macro_collect"),
    path("download/local-agent.exe", macro_download_local_agent_exe, name="macro_download_local_agent_exe"),
    path("download/local-agent-mac.zip", macro_download_local_agent_mac, name="macro_download_local_agent_mac"),
    path("download/local-agent.py", macro_download_local_agent_py, name="macro_download_local_agent_py"),
    path("download/local-agent.bat", macro_download_local_agent_bat, name="macro_download_local_agent_bat"),
    path("delete/filtered/", macro_delete_filtered, name="macro_delete_filtered"),
    path("delete/blocked/", macro_delete_blocked, name="macro_delete_blocked"),
    path("delete/all/", macro_delete_all, name="macro_delete_all"),
    path("delete/runs/", macro_delete_runs, name="macro_delete_runs"),
    path("delete/source/", macro_delete_source, name="macro_delete_source"),
    path("delete/run/<int:run_id>/", macro_delete_run_item, name="macro_delete_run_item"),
    path("lead/<int:lead_id>/block/", macro_toggle_phone_block, {"blocked": True}, name="macro_block_phone"),
    path("lead/<int:lead_id>/unblock/", macro_toggle_phone_block, {"blocked": False}, name="macro_unblock_phone"),
    path("export/", macro_export_csv, name="macro_export_csv"),
    path("export/xlsx/", macro_export_xlsx, name="macro_export_xlsx"),
    path("import/", macro_import_csv, name="macro_import_csv"),
    path("api/import/", macro_api_import, name="macro_api_import"),
]
